using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class WeaponController : MonoBehaviour
{

    public GameObject Sword;
   //public bool CanAttack = true;
    public float AttackCooldown = 1.0f;
    Animator anim;
    //public AudioClip SwordAttackSound;
    //public bool isAttacking = false;
    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetMouseButton(0))
        {
            //if (CanAttack)
            //{
                SwordAttack();
            //}
        }
    }
    public void SwordAttack()
    {
        //isAttacking = true;
        //CanAttack = false;
        //Animator anim = Sword.GetComponent<Animator>();
        //anim.SetTrigger("Attack");
        //AudioSource ac = GetComponent<AudioSource>();
        //ac.PlayOneShot(SwordAttackSound);
        //StartCoroutine(ResetAttackCoolDown());
    }


    //IEnumerator ResetAttackCoolDown()
    //{
    //    StartCoroutine(ResetAttackBool());
    //    yield return new WaitForSeconds(AttackCooldown);
    //    //CanAttack = true;
    //}

    IEnumerator ResetAttackBool()
    {

        yield return new WaitForSeconds(1.0f);
        //isAttacking = false;
    }
}